# The Docker image that will be used to build your app
image: node:20.16.0

stages:
  - build
  - deploy

# Define the build stage
build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

# Define the deploy stage
pages:
  stage: deploy
  script:
    - mv ./dist ./public
  artifacts:
    paths:
      - public/
  rules:
    # Ensure that only pushes to the default branch trigger a deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
